### PR TITLE
Issue-6

### PR DESCRIPTION
**Pull request by tuanthanh2067**
Improve function **processFile** so that it can convert .md file to .html.

### CODE REVIEW

**Review by minhhang107 — CHANGES_REQUESTED** [review]
The way you implement the markdown looks great. I have some suggestions for improvement:
- [x] The logic for .txt and .md is almost the same except how to generate the `content` so you might consider removing duplicating code
- [x] You may need to handle the output name so it won't contain .md extension. Currently it's only removing .txt from the output file name
- [x] Please update the Readme with the new feature

Many thanks!

**Comment by tuanthanh2067** [comment]
Sure, I'll fix that right now.

**Comment by minhhang107** [comment]
I see your point. Then please make sure you clarify in Readme that the feature parsing title is only applied to .txt file.

**Comment by tuanthanh2067** [comment]
Instead of removing .txt or .md extension outside of `fs.readFile()` I'd like to move it inside so we don't have to have another if else case outside.

**Review by minhhang107 — APPROVED** [review]
Everything looks great now!

**Pull request merged**
